# Generated by Django 4.1 on 2022-12-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.FloatField(blank=True, null=True, verbose_name='Jumlah Anggaran')),
                ('deskripsi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Deskripsi Anggaran')),
                ('kategori', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kategori Anggaran')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
        ),
    ]
