# Generated by Django 4.1 on 2022-12-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategori', '0001_initial'),
        ('anggaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggaran',
            name='kategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kategori.kategori'),
        ),
        migrations.AddField(
            model_name='anggaran',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
