# Generated by Django 4.1 on 2022-12-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0003_alter_kategori_jenis_kategori'),
        ('anggaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggaran',
            name='kategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kategori.kategori'),
        ),
    ]
