# Generated by Django 4.1 on 2022-12-04 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konsultan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Dibatalkan', 'Dibatalkan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Sedang Berlangsung', 'Sedang Berlangsung'), ('Selesai', 'Selesai')], default='Menunggu Persetujuan', max_length=25)),
                ('alasan', models.TextField(verbose_name='Alasan Konsultasi')),
                ('tanggal', models.DateField(verbose_name='Tanggal Konsultasi')),
                ('tanggal_diajukan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('klien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('konsultan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konsultan.konsultan')),
            ],
        ),
    ]
