# Generated by Django 4.1 on 2022-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultasi',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
