# Generated by Django 4.1 on 2022-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icons',
        ),
        migrations.RenameField(
            model_name='kategori',
            old_name='jenis_transaksi',
            new_name='jenis_kategori',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='icon',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
