# Generated by Django 4.1 on 2022-12-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catatanTransaksi', '0001_initial'),
        ('kategori', '0002_delete_icons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='jenis_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catatanTransaksi.jenistransaksi'),
        ),
    ]
