# Generated by Django 4.1 on 2022-12-10 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategori', '0003_alter_kategori_jenis_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='kategori',
            unique_together={('user', 'nama')},
        ),
    ]
