# Generated by Django 4.1 on 2022-12-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.PositiveSmallIntegerField(choices=[(1, 'Pemasukan'), (2, 'Pengeluaran')])),
            ],
        ),
        migrations.CreateModel(
            name='CatatanTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Deskripsi Transaksi')),
                ('nominal', models.FloatField(verbose_name='Jumlah Transaksi')),
                ('tanggal', models.DateField(verbose_name='Tanggal Transaksi')),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catatanTransaksi.jenistransaksi')),
            ],
        ),
    ]
