# Generated by Django 4.1 on 2022-12-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Deskripsi Transaksi')),
                ('nominal', models.FloatField(blank=True, null=True, verbose_name='Jumlah Transaksi')),
                ('tanggal', models.DateField(verbose_name='Tanggal Transaksi')),
                ('kategori', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kategori Transaksi')),
                ('pencatat_keuangan', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pencatat Keuangan')),
                ('laporan_keuangan', models.CharField(blank=True, max_length=30, null=True, verbose_name='Laporan Keuangan')),
                ('jenis', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jenis Transaksi')),
            ],
        ),
    ]
