# Generated by Django 4.1 on 2022-12-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategori', '0001_initial'),
        ('catatanTransaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catatantransaksi',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kategori.kategori'),
        ),
        migrations.AddField(
            model_name='catatantransaksi',
            name='pencatat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
