# Generated by Django 4.1 on 2022-12-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatanTransaksi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatantransaksi',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deskripsi Transaksi'),
        ),
    ]
